/**
 * @aiq.webdesigner
 * This script requires AIQ Web Designer
*/
setShadowDOM(true);
navigateTo("https://demosite.appvance.net/");
if (assertTextPresent("Rails")){
   var var1=true;
}
log(var1);
click(fallback(`span(0, _in(div("product_1")))`,
   `span(0, _in(div({'id':'product_1'})))`,
   `span("info")`,
   `byJQuery('.info')`,
   `span("Ruby on Rails Tote")`,
   `span("Ruby on Rails Tote")`,
   `byJQuery('span[class="info"]')`,
   `byJQuery('span[title="Ruby on Rails Tote"]')`,
   `byXPath('//*[@class="info"]')`,
   `byXPath('//*[text()="Ruby on Rails Tote"]')`,
   `byXPath("//div[@id='product_1']/div/div[1]/a/span")`,
   `byXPath("id('product_1')/div[@class='panel panel-default']/div[@class='panel-body text-center product-body']/a[1]/span[@class='info']")`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/div/div/div/a/span')`));
setValue(fallback(`byXPath('//*[@id="quantity"]')`,
   `numberbox("quantity")`,
   `numberbox("quantity")`,
   `byJQuery('#quantity')`,
   `byXPath("id('quantity')")`,
   `byJQuery('input[name="quantity"]')`,
   `numberbox("form-control title")`,
   `byXPath('//*[@name="quantity"]')`,
   `byXPath("//input[@id='quantity']")`,
   `byXPath('//*[@class="title form-control"]')`,
   `byJQuery('div[class="row"] > div[class="col-md-5"] > div[class="add-to-cart"] > div[class="input-group"] > input[class="title form-control"]')`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/div/div/div[2]/form/div/div/div[2]/div/input')`),"2");
click(fallback(`submit(0, _in(div("inside-product-cart-form")))`,
   `submit(0, _in(div({'id':'inside-product-cart-form'})))`,
   `submit("button")`,
   `submit("Add To Cart")`,
   `byJQuery('button[name="button"]')`,
   `submit("btn btn-success[1]")`,
   `byXPath('//*[@name="button"]')`,
   `submit("add-to-cart-button")`,
   `byJQuery('#add-to-cart-button')`,
   `byXPath("id('add-to-cart-button')")`,
   `byXPath('//*[@id="add-to-cart-button"]')`,
   `byXPath("//button[@id='add-to-cart-button']")`,
   `byJQuery('div[class="col-md-5"] > div[class="add-to-cart"] > div[class="input-group"] > span[class="input-group-btn"] > button[class="btn btn-success"]')`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/div/div/div[2]/form/div/div/div[2]/div/span/button')`));
click(fallback(`link(0, _in(paragraph("clear_cart_link")))`,
   `link(0, _in(paragraph({'id':'clear_cart_link'})))`,
   `link("continue")`,
   `link("Continue shopping")`,
   `byJQuery('a[class="continue"]')`,
   `byJQuery('#clear_cart_link > .continue')`,
   `link("/products")`,
   `byJQuery('a[href="/products"]')`,
   `byXPath("id('clear_cart_link')/a[@class='continue']")`,
   `byXPath('//*[@class="continue"]')`,
   `byXPath('//*[text()="Continue shopping"]')`,
   `byXPath("//p[@id='clear_cart_link']/a")`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/form/p/a')`));
click(fallback(`span(0, _in(div("product_5")))`,
   `span(0, _in(div({'id':'product_5'})))`,
   `span("info[4]")`,
   `span("Ruby on Rails Ringer T-Shirt")`,
   `span("Ruby on Rails Ringer T-Shirt")`,
   `byJQuery('span[title="Ruby on Rails Ringer T-Shirt"]')`,
   `byXPath('//*[text()="Ruby on Rails Ringer T-Shirt"]')`,
   `byXPath("//div[@id='product_5']/div/div[1]/a/span")`,
   `byXPath("id('product_5')/div[@class='panel panel-default']/div[@class='panel-body text-center product-body']/a[1]/span[@class='info']")`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/div[5]/div/div/a/span')`));
setText(fallback(`byXPath('//*[@id="quantity"]')`,
   `numberbox("quantity")`,
   `numberbox("quantity")`,
   `byJQuery('#quantity')`,
   `byXPath("id('quantity')")`,
   `byJQuery('input[value="1"]')`,
   `byJQuery('input[name="quantity"]')`,
   `numberbox("form-control title")`,
   `byXPath('//*[@name="quantity"]')`,
   `byXPath("//input[@id='quantity']")`,
   `byXPath('//*[@class="title form-control"]')`,
   `byJQuery('div[class="row"] > div[class="col-md-5"] > div[class="add-to-cart"] > div[class="input-group"] > input[class="title form-control"]')`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/div/div/div[2]/form/div/div/div[2]/div/input')`),"2");
click(fallback(`submit(0, _in(div("inside-product-cart-form")))`,
   `submit(0, _in(div({'id':'inside-product-cart-form'})))`,
   `submit("button")`,
   `submit("Add To Cart")`,
   `byJQuery('button[name="button"]')`,
   `submit("btn btn-success[1]")`,
   `byXPath('//*[@name="button"]')`,
   `submit("add-to-cart-button")`,
   `byJQuery('#add-to-cart-button')`,
   `byXPath("id('add-to-cart-button')")`,
   `byXPath('//*[@id="add-to-cart-button"]')`,
   `byXPath("//button[@id='add-to-cart-button']")`,
   `byJQuery('div[class="col-md-5"] > div[class="add-to-cart"] > div[class="input-group"] > span[class="input-group-btn"] > button[class="btn btn-success"]')`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/div/div/div[2]/form/div/div/div[2]/div/span/button')`));
navigateTo("https://demosite.appvance.net/cart?variant_id=7");
click(fallback(`link(0, _in(paragraph("clear_cart_link")))`,
   `link(0, _in(paragraph({'id':'clear_cart_link'})))`,
   `link("continue")`,
   `link("Continue shopping")`,
   `byJQuery('a[class="continue"]')`,
   `byJQuery('#clear_cart_link > .continue')`,
   `link("/products")`,
   `byJQuery('a[href="/products"]')`,
   `byXPath("id('clear_cart_link')/a[@class='continue']")`,
   `byXPath('//*[@class="continue"]')`,
   `byXPath('//*[text()="Continue shopping"]')`,
   `byXPath("//p[@id='clear_cart_link']/a")`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/form/p/a')`));
click(fallback(`span(0, _in(div("product_3")))`,
   `span(0, _in(div({'id':'product_3'})))`,
   `span("info[2]")`,
   `span("Ruby on Rails Baseball Jersey")`,
   `span("Ruby on Rails Baseball Jersey")`,
   `byJQuery('span[title="Ruby on Rails Baseball Jersey"]')`,
   `byXPath('//*[text()="Ruby on Rails Baseball Jersey"]')`,
   `byXPath("//div[@id='product_3']/div/div[1]/a/span")`,
   `byXPath("id('product_3')/div[@class='panel panel-default']/div[@class='panel-body text-center product-body']/a[1]/span[@class='info']")`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/div[3]/div/div/a/span')`));
click(fallback(`submit(0, _in(div("inside-product-cart-form")))`,
   `submit(0, _in(div({'id':'inside-product-cart-form'})))`,
   `submit("button")`,
   `submit("Add To Cart")`,
   `byJQuery('button[name="button"]')`,
   `submit("btn btn-success[1]")`,
   `byXPath('//*[@name="button"]')`,
   `submit("add-to-cart-button")`,
   `byJQuery('#add-to-cart-button')`,
   `byXPath("id('add-to-cart-button')")`,
   `byXPath('//*[@id="add-to-cart-button"]')`,
   `byXPath("//button[@id='add-to-cart-button']")`,
   `byJQuery('div[class="col-md-5"] > div[class="add-to-cart"] > div[class="input-group"] > span[class="input-group-btn"] > button[class="btn btn-success"]')`,
   `byXPath('/html/body/div[2]/div/div/div/div[2]/div/div/div[2]/form/div/div[2]/div[2]/div/span/button')`));
include("{ds}/Library.ds");
//click(fallback(`submit(1, _in(form("update-cart")))`,
//   `submit(1, _in(form({'id':'update-cart'})))`,
//   `byXPath('//*[@id="checkout-link"]')`,
//   `submit("btn btn-lg btn-success")`,
//   `byXPath('//*[@name="checkout"]')`,
//   `submit("checkout-link")`,
//   `submit("checkout")`,
//   `submit("Checkout")`,
//   `byXPath("//button[@id='checkout-link']")`,
//   `byXPath('//*[@class="btn btn-lg btn-success"]')`,
//   `byXPath('/html/body/div[2]/div/div/div/div/form/div/div[2]/div/button[2]')`,
//   `byXPath("id('checkout-link')")`,
//   `byJQuery('div[class="links col-md-3 navbar-form pull-right text-right"] > div[class="form-group"] > button[class="btn btn-lg btn-success"]')`,
//   `byJQuery('#checkout-link')`,
//   `byJQuery('button[name="checkout"]')`));
//setValue(fallback(`byXPath('//*[@id="order_email"]')`,
//   `emailbox("form-control title")`,
//   `byXPath('//*[@name="order[email]"]')`,
//   `emailbox("order_email")`,
//   `emailbox("order[email]")`,
//   `byXPath("//input[@id='order_email']")`,
//   `byXPath('//*[@class="form-control title"]')`,
//   `byXPath('/html/body/div[2]/div/div/div/div[2]/div/div[2]/form/p/input')`,
//   `byXPath("id('order_email')")`,
//   `byJQuery('input[class="form-control title"]')`,
//   `byJQuery('#order_email')`,
//   `byJQuery('input[name="order[email]"]')`),"demo@gmail.com");
//click(fallback(`submit("btn btn-block btn-lg btn-success[1]")`,
//   `submit("commit[1]")`,
//   `submit("Continue")`,
//   `byXPath("//form[@id='checkout_form_registration']/p[2]/input")`,
//   `byXPath('/html/body/div[2]/div/div/div/div[2]/div/div[2]/form/p[2]/input')`,
//   `byXPath("id('checkout_form_registration')/p[2]/input[@class='btn btn-lg btn-success btn-block']")`,
//   `submit({'data-disable-with':'Continue'})`,
//   `byJQuery('input[value="Continue"]')`));
